version: "3.9"
services:
  sshtunnel:
    container_name: ssh-tunnel
    build: ..
    restart: unless-stopped
    depends_on:
      - nginx-hello
      - openssh-server
    volumes:
      - ./ssh/ed_key:/ssh_key:ro \
    environment:
      - SSH_PORT=2222
      - SSH_USER=proxy
      - LOCAL_IP=nginx-hello
      - LOCAL_PORT=80
      - GATEWAY_IP=openssh-server
      - REMOTE_IP=*
      - REMOTE_PORT=8080

  nginx-hello:
    container_name: nginx-hello
    image: nginxdemos/hello

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY_FILE=/tmp/ed_key.pub
      - USER_NAME=proxy
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel # important if you're using linuxserver/openssh as a reverse proxy
    volumes:
      - ./ssh/ed_key.pub:/tmp/ed_key.pub:ro \
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  default:
    driver: bridge
